server:
    port: 10109

spring:
    profiles: 
        active: prod
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://CCWSQL02;databaseName=CID
        username: Development
        password: password4Development
        initialize: false
        initialSize: 10
        maxActive: 100
        maxIdle: 10
        minIdle: 10
        
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2008Dialect
        show_sql: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

    data: 
        jpa: 
            repositories.enabled: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipster

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
            